name: location-catalog

services:
  health:
    image: location-catalog:health
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      LOG_LEVEL: info
    ports:
      - "9000:8080"
